### ISSUE TITLE
Cannot open include file "Hl.h"

### ISSUE THREAD

**Issue by PizzaCutter** [haddock7/hlimgui#7]
Followed the instructions to build the hlimgui but gives the error "cannot open include file: 'hl.h' Is this maybe missing from the repository or should I grab this header file from somewhere else?

**Comment by haddock7** [comment]
When you install HashLink binaries on your system, it installs also headers (including `hl.h`) and libraries.

On Windows, the environment variable `HASHLINKPATH` should be automatically defined and is used in CMakeLists.txt. If it's not defined, please create it and set its value to the path of the HashLink install directory.

On Linux, the installation should have copied headers and libraries in your system folders, so it should be available immediately.
