### ISSUE TITLE
No way to register textures with imgui

### ISSUE THREAD

**Issue by nspitko** [haddock7/hlimgui#9]
`ImGuiDrawableBuffers` defines a path for linking heaps textures with imgui, however, the entire class is private.

A quick fix is to just remove the private qualifier, but it's less than ideal from an API standpoint. I'm also not entirely sure how Heaps would react if you called `dispose()` but were sharing in-use textures with imgui.

**Comment by haddock7** [comment]
Hi @nspitko  sorry I haven't worked on this project for a long time now, and I don't plan to continue it in the future.
